# Generated by Django 5.1.7 on 2025-04-06 06:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_product_category"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="Category",
            new_name="category",
        ),
    ]
